### ISSUE TITLE
Emerald Wallet

### ISSUE THREAD

**Issue by Bonaventur** [ethereumclassic/faq#11]
We have sent ETC from our Exodus wallet to our Emerald wallet. The ETC is not in our emerald wallet, no access, nothing. We are most concerned about this, We are thankful we did not send all our ETC to Emerald wallet. Please advise as to where our ETC are asap. Thank you
![screen shot 2018-01-07 at 5 51 40 am](https://user-images.githubusercontent.com/35195564/34651450-420e9e04-f385-11e7-85bc-c6141bebb24d.jpg)

**Comment by splix** [comment]
ETC are at address `0xdff7d172...`, as you see from the picture. 

If you don't see them in Emerald (which means you didn't synchronize it yet), open this address in MyEtherWallet or any other ETC-compatible wallet instead

**Comment by Bonaventur** [comment]
Still no access to the ETC we sent to our address from Exodus Wallet? 
![screen shot 2018-01-07 at 2 20 57 pm](https://user-images.githubusercontent.com/35195564/34654892-a7a7de48-f3b6-11e7-953a-96e79ce8f4ec.jpg)

**Comment by Bonaventur** [comment]
Thank you    ...located via myetherwallet/etc network...
