### ISSUE TITLE
Deposit to Eidoo Wallet

### ISSUE THREAD

**Issue by Preddy1980** [ethereumclassic/faq#12]
Hi,
A deposit of ETC is stuck going into my EIDOO wallet can you undo the transaction?

Transaction 0x6364c14449on Ethereum Classic
Transaction Details
Timestamp
Feb 13, 2018 7:54 PM
Confirmations
4384
Value
1.0400 Ether
 
1040000000000000000 Wei
 
$35.34
 
 
Hash
0x6364c14449a3b8b64e62dc6a0965eef8f8538d18b4cd7dcad3228f714b8bc2fb

**Comment by cseberino** [comment]
https://medium.com/@cseberino/when-absolutely-no-one-can-steal-or-return-lost-ethereum-classic-funds-bce296774e69

**Comment by Preddy1980** [comment]
Always a way
They are retrievable since you sent it to a wallet that has a private key, I had similar problem and was able to save over 50 etc.

You can retrieve Eidoo’s private key using the backup phrase (12 words) through an external tool. Follow the directions below:

Connect to https://iancoleman.github.io/bip39/1 (for greater security the tool also works with the computer off-line)

In the Mnemonic section type the 12 words in the BIP39 Mnemonic field and set the Coin field to ETH-Ethereum

In the Derivation Path section choose the BIP32 tab and set the BIP32 Derivation Path field with this value: m/44’/60’/0

Check that all data you entered is correct and moved down in the Derived Addresses section

Your private key is the one you find in the first line of the table, under the Private Key column.
